export const desktopTeam = [
  {
    name: "Rustam Rahmatov",
    url: "rustam.svg",
    position: "CEO",
    link: "https://www.linkedin.com/in/rustamrahmatov/",
    about: "CEO_about",
    text: "CEO_text",
    content: "CEO_text_second",
    vizyon: "Rustam Rahmatov vision",
    ocupation: "Rustam Rahmatov ocupation",
    aims: "",
  },
  {
    name: "Mark Zubov",
    url: "mark.svg",
    position: "CFO",
    link: "https://www.linkedin.com/in/markzubov/",
    about: "CFO_about",
    text: "CFO_text",
    content: "CFO_text_second",
    vizyon: "Mark Zubov vision",
    ocupation: "Mark Zubov ocupation",
    aims: "",
  },
  {
    name: "Suna Park",
    url: "suno.svg",
    position: "EDU",
    link: "https://www.linkedin.com/in/suna-julia-park-ab1a0613/",
    about: "EDU_about",
    text: "EDU_text",
    content: "EDU_text_second",
    vizyon: "EDU_vizyon",
    ocupation: "Suna Park ocupation",
    aims: "",
  },
  {
    name: "Timur Khodjaev",
    url: "timur.svg",
    position: "NMMC",
    link: "https://www.linkedin.com/in/%D1%82%D0%B8%D0%BC%D1%83%D1%80-%D1%85%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2-2665a0105/",
    about: "NMMC_about",
    text: "NMMC_text",
    content: "NMMC_text_second",
    vizyon: "Timur Khodjaev vision",
    ocupation: "Timur Khodjaev ocupation",
    aims: "",
  },
  {
    name: "Dr Ziyaad Mahomed",
    url: "doktor.svg",
    position: "SHARIA",
    link: "https://www.linkedin.com/in/dr-ziyaad-mahomed-2309a516/",
    about: "SHARIA_about",
    text: "SHARIA_text",
    content: "SHARIA_text_second",
    vizyon: "Dr Ziyaad Mahomed vision",
    ocupation: "Dr Ziyaad Mahomed ocupation",
    aims: "",
  },
  {
    name: "Timur Salikhbaev",
    url: "timur2.svg",
    position: "LAW",
    link: "https://www.linkedin.com/in/timur-salikhbaev-5375881a8/",
    about: "LAW_about",
    text: "LAW_text",
    content: "LAW_text_second",
    vizyon: "Timur Salikhbaev vision",
    ocupation: "Timur Salikhbaev ocupation",
    aims: "",
  },
  {
    name: "Arjun Batra",
    url: "arjun.svg",
    position: "TECH",
    link: "https://www.linkedin.com/in/batraarjun/",
    about: "TECH_about",
    text: "TECH_text",
    content: "TECH_text_second",
    vizyon: "Arjun Batra vision",
    ocupation: "Arjun Batra ocupation",
    aims: "",
  },
  {
    name: "A.J. Davidson",
    url: "davidson.svg",
    position: "TECH",
    link: "https://www.linkedin.com/in/a-j-davidson-4b4ab184/",
    about: "AJ_about",
    text: "AJ_text",
    content: "AJ_text_second",
    vizyon: "",
    ocupation: "",
    aims: "",
  },
  {
    name: "Izzat Shukurov",
    url: "izzat.svg",
    position: "MARKET",
    link: "https://www.linkedin.com/in/izzatshukurov/",
    about: "MARKET_about",
    text: "MARKET_text",
    content: "MARKET_text_second",
    vizyon: "Izzat Shukurov vision",
    ocupation: "Izzat Shukurov ocupation",
    aims: "",
  },
  {
    name: "Kirill Sevastyanenko",
    url: "kiril.svg",
    position: "AI",
    link: "https://www.linkedin.com/in/kirillseva/",
    about: "AI_about",
    text: "AI_text",
    content: "AI_text_second",
    vizyon: "",
    ocupation: "Kirill Sevastyanenko ocupation",
    aims: "",
  },
  {
    name: "Djakhongir Makhamov",
    url: "jahongir.svg",
    position: "DJ",
    link: "https://www.linkedin.com/in/djahon/",
    about: "DJ_about",
    text: "DJ_text",
    content: "DJ_text_second",
    vizyon: "DJ_vizyon",
    ocupation: "DJ_ocup",
    aims: "DJ_aims",
  },
  {
    name: "Indira Akramova",
    url: "indira.svg",
    position: "PM",
    link: "https://www.linkedin.com/in/indira-akramova-ergasheva-58aa3b51/",
    about: "PM_about",
    text: "PM_text",
    content: "PM_text_second",
    vizyon: "PM_vizyon",
    ocupation: "PM_ocup",
    aims: "",
  },
];

export const mobileTeam = [
  [
    {
      name: "Rustam Rahmatov",
      url: "rustam.svg",
      position: "CEO",
      link: "https://www.linkedin.com/in/rustamrahmatov/",
      about: "CEO_about",
      text: "CEO_text",
      content: "CEO_text_second",
      vizyon: "Rustam Rahmatov vision",
      ocupation: "Rustam Rahmatov ocupation",
      aims: "",
    },
    {
      name: "Mark Zubov",
      url: "mark.svg",
      position: "CFO",
      link: "https://www.linkedin.com/in/markzubov/",
      about: "CFO_about",
      text: "CFO_text",
      content: "CFO_text_second",
      vizyon: "Mark Zubov vision",
      ocupation: "Mark Zubov ocupation",
      aims: "",
    },
    {
      name: "Suna Park",
      url: "suno.svg",
      position: "EDU",
      link: "https://www.linkedin.com/in/suna-julia-park-ab1a0613/",
      about: "EDU_about",
      text: "EDU_text",
      content: "EDU_text_second",
      vizyon: "EDU_vizyon",
      ocupation: "Suna Park ocupation",
      aims: "",
    },
    {
      name: "Timur Khodjaev",
      url: "timur.svg",
      position: "NMMC",
      link: "https://www.linkedin.com/in/%D1%82%D0%B8%D0%BC%D1%83%D1%80-%D1%85%D0%BE%D0%B4%D0%B6%D0%B0%D0%B5%D0%B2-2665a0105/",
      about: "NMMC_about",
      text: "NMMC_text",
      content: "NMMC_text_second",
      vizyon: "Timur Khodjaev vision",
      ocupation: "Timur Khodjaev ocupation",
      aims: "",
    },
    {
      name: "Dr Ziyaad Mahomed",
      url: "doktor.svg",
      position: "SHARIA",
      link: "https://www.linkedin.com/in/dr-ziyaad-mahomed-2309a516/",
      about: "SHARIA_about",
      text: "SHARIA_text",
      content: "SHARIA_text_second",
      vizyon: "Dr Ziyaad Mahomed vision",
      ocupation: "Dr Ziyaad Mahomed ocupation",
      aims: "",
    },
    {
      name: "Timur Salikhbaev",
      url: "timur2.svg",
      position: "LAW",
      link: "https://www.linkedin.com/in/timur-salikhbaev-5375881a8/",
      about: "LAW_about",
      text: "LAW_text",
      content: "LAW_text_second",
      vizyon: "Timur Salikhbaev vision",
      ocupation: "Timur Salikhbaev ocupation",
      aims: "",
    },
  ],
  [
    {
      name: "Arjun Batra",
      url: "arjun.svg",
      position: "TECH",
      link: "https://www.linkedin.com/in/batraarjun/",
      about: "TECH_about",
      text: "TECH_text",
      content: "TECH_text_second",
      vizyon: "Arjun Batra vision",
      ocupation: "Arjun Batra ocupation",
      aims: "",
    },
    {
      name: "A.J. Davidson",
      url: "davidson.svg",
      position: "TECH",
      link: "https://www.linkedin.com/in/a-j-davidson-4b4ab184/",
      about: "AJ_about",
      text: "AJ_text",
      content: "AJ_text_second",
      vizyon: "",
      ocupation: "",
      aims: "",
    },
    {
      name: "Izzat Shukurov",
      url: "izzat.svg",
      position: "MARKET",
      link: "https://www.linkedin.com/in/izzatshukurov/",
      about: "MARKET_about",
      text: "MARKET_text",
      content: "MARKET_text_second",
      vizyon: "Izzat Shukurov vision",
      ocupation: "Izzat Shukurov ocupation",
      aims: "",
    },
    {
      name: "Kirill Sevastyanenko",
      url: "kiril.svg",
      position: "AI",
      link: "https://www.linkedin.com/in/kirillseva/",
      about: "AI_about",
      text: "AI_text",
      content: "AI_text_second",
      vizyon: "",
      ocupation: "Kirill Sevastyanenko ocupation",
      aims: "",
    },
    {
      name: "Djakhongir Makhamov",
      url: "jahongir.svg",
      position: "DJ",
      link: "https://www.linkedin.com/in/djahon/",
      about: "DJ_about",
      text: "DJ_text",
      content: "DJ_text_second",
      vizyon: "DJ_vizyon",
      ocupation: "DJ_ocup",
      aims: "DJ_aims",
    },
    {
      name: "Indira Akramova",
      url: "indira.svg",
      position: "PM",
      link: "https://www.linkedin.com/in/indira-akramova-ergasheva-58aa3b51/",
      about: "PM_about",
      text: "PM_text",
      content: "PM_text_second",
      vizyon: "PM_vizyon",
      ocupation: "PM_ocup",
      aims: "",
    },
  ],
];
