export const news = [
  {
    image: "images/lastNews/news1.jpg",
    title: "news_title_1",
    modalImg: "images/lastNews/news1.jpg",
    day: "13",
    month: "june",
    year: "2022",
    modalDescr: "news_description_1",
  },
  {
    image: "/images/newDesign/newSecond.svg",
    title: "news_title_2",
    modalImg: "/images/newDesign/newSecond.svg",
    day: "3",
    month: "june",
    year: "2022",
    modalDescr: "news_description_2",
  },
  {
    image: "images/lastNews/news2.jpg",
    title: "news_title_3",
    modalImg: "images/lastNews/news2.jpg",
    day: "27",
    month: "may",
    year: "2022",
    modalDescr: "news_description_3",
  },
  {
    image: "images/lastNews/news3.jpg",
    title: "news_title_4",
    modalImg: "images/lastNews/news3.jpg",
    day: "9",
    month: "june",
    year: "2022",
    modalDescr: "news_description_4",
  },
  {
    image: "/images/newDesign/newSecond.svg",
    title: "news_title_5",
    modalImg: "/images/newDesign/newSecond.svg",
    day: "22",
    month: "february",
    year: "2022",
    modalDescr: "news_description_5",
  },
];
